name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feat

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      # https://github.com/pre-commit/pre-commit.com/blob/main/sections/advanced.md#temporarily-disabling-hooks
      # mutliple hooks: comma separated list, whitespace OK
      # poetry-lock: different dependencies btw ARM cloud runner & x86 local dev
      SKIP: poetry-lock

    strategy:
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: poetry install
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.9
          poetry-version: 2.0.0

      - name: pre-commit
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all-files

      - name: pytest
        run: |
          poetry run pytest
